name: leakpro_test
channels:
  - conda-forge
dependencies:
  - numpy
  - pytorch
  - torchvision
  - dotmap
  - loguru
  - matplotlib
  - jinja2
  - pandas
  - seaborn
  - pillow
  - scipy
  - scikit-learn
  - pytest
  - python>=3.9 
  - pip:
    - pyyaml

