name: leakpro
channels:
  - conda-forge
dependencies:
  - dotmap>=1.3.30 # core non-optional dependency
  - loguru>=0.6.0 # core non-optional dependency
  - matplotlib>=3.6.0 # core non-optional dependency
  - numpy==1.23.5 # core non-optional depedency
  - pytest # for tests
  - python>=3.9 # core non-optional dependency