audit:  # Configurations for auditing
  random_seed: 1234  # Integer specifying the random seed
  attack_list:
    lira:
      training_data_fraction: 0.5  # Fraction of the auxilary dataset to use for this attack (in each shadow model training)
      num_shadow_models: 5 # Number of shadow models to train
      online: False # perform online or offline attack
      fixed_variance: False # Use a fixed variance for the whole audit

  report_log: "./leakpro_output/results"  # Folder to save the auditing report
  target_model_folder: "./target"
  attack_folder: "attack_objects"
  attack_type: "mia"
  split_method: "no_overlapping"  # Method of creating the attack dataset

target:
  module_path: "./leakpro/shadow_model_blueprints.py"
  model_class: "ResNet18"
  trained_model_path: "./target/target_model.pkl" 
  trained_model_metadata_path: "./target/model_metadata.pkl"
  data_path: "./target/data/cifar10.pkl"


shadow_model:
  storage_path: "./leakpro_output/attack_objects/shadow_models"
  # Path to a Python file with the shadow model architecture
  module_path: "./leakpro/shadow_model_blueprints.py"
  #
  # [Optional] Define a shadow model (if none, shadow model will follow the target model)
  # Name of the class to instantiate from the specified file
  model_class_path: "ResNet18" #"ConvNet"
  optimizer: 
    name: sgd #adam, sgd, rmsprop
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0
  loss: 
    name: crossentropyloss # crossentropyloss, nllloss, mseloss
  # Initialization parameters
  init_params: {}


